// AUTO-GENERATED by @hono/inertia/vite. Do not edit.
import type app from '../server/index'

export type PageName = 'DailyHabits' | 'Dashboard' | 'Home' | 'Login' | 'Privacy' | 'Terms' | 'WeeklyHabits'

declare module '@hono/inertia' {
  interface InertiaPages {
    'DailyHabits': unknown
    'Dashboard': unknown
    'Home': unknown
    'Login': unknown
    'Privacy': unknown
    'Terms': unknown
    'WeeklyHabits': unknown
  }
  interface AppRegistry {
    app: typeof app
  }
}

export type { PageProps } from '@hono/inertia'
